apiVersion: batch/v1
kind: CronJob
metadata:
  name: send-reminders
spec:
  schedule: "30 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: send-reminders
            image: 715633473519.dkr.ecr.us-east-1.amazonaws.com/graphacademy
            imagePullPolicy: IfNotPresent
            command:
            - npm
            - run
            - cmd:reminders
            env:

            - name: BASE_URL
              valueFrom:
                secretKeyRef:
                  name: ga-secrets
                  key: BASE_URL
            - name: NEO4J_HOST
              valueFrom:
                secretKeyRef:
                  name: ga-secrets
                  key: NEO4J_HOST
            - name: NEO4J_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: ga-secrets
                  key: NEO4J_PASSWORD
            - name: NEO4J_USERNAME
              valueFrom:
                secretKeyRef:
                  name: ga-secrets
                  key: NEO4J_USERNAME
            - name: MAILGUN_API_KEY
              valueFrom:
                secretKeyRef:
                  name: ga-secrets
                  key: MAILGUN_API_KEY
            - name: MAILGUN_DOMAIN
              valueFrom:
                secretKeyRef:
                  name: ga-secrets
                  key: MAILGUN_DOMAIN
            - name: MAIL_FROM
              valueFrom:
                secretKeyRef:
                  name: ga-secrets
                  key: MAIL_FROM
            - name: MAIL_REPLY_TO
              valueFrom:
                secretKeyRef:
                  name: ga-secrets
                  key: MAIL_REPLY_TO
          restartPolicy: OnFailure