apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: graphacademy
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: graphacademy
  minReplicas: 3
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50