apiVersion: apps/v1
kind: Deployment
metadata:
  name: graphacademy
spec:
  template:
    spec:
      containers:
        - env:
            - name: ASCIIDOC_DIRECTORY
              valueFrom:
                configMapKeyRef:
                  name: ga-config-map
                  key: ASCIIDOC_DIRECTORY
            - name: AUTH0_CLIENT_ID
              valueFrom:
                configMapKeyRef:
                  name: ga-config-map
                  key: AUTH0_CLIENT_ID
            - name: AUTH0_CLIENT_SECRET
              valueFrom:
                configMapKeyRef:
                  name: ga-config-map
                  key: AUTH0_CLIENT_SECRET
            - name: AUTH0_ISSUER_BASE_URL
              valueFrom:
                configMapKeyRef:
                  name: ga-config-map
                  key: AUTH0_ISSUER_BASE_URL
            - name: NEO4J_HOST
              valueFrom:
                configMapKeyRef:
                  name: ga-config-map
                  key: NEO4J_HOST
            - name: NEO4J_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: ga-config-map
                  key: NEO4J_PASSWORD
            - name: NEO4J_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: ga-config-map
                  key: NEO4J_USERNAME
            - name: SANDBOX_URL
              valueFrom:
                configMapKeyRef:
                  name: ga-config-map
                  key: SANDBOX_URL
            - name: MAILGUN_DOMAIN
              valueFrom:
                configMapKeyRef:
                  name: ga-config-map
                  key: MAILGUN_DOMAIN
            - name: MAILGUN_API_KEY
              valueFrom:
                configMapKeyRef:
                  name: ga-config-map
                  key: MAILGUN_API_KEY
            - name: MAIL_FROM
              valueFrom:
                configMapKeyRef:
                  name: ga-config-map
                  key: MAIL_FROM
            - name: MAIL_REPLY_TO
              valueFrom:
                configMapKeyRef:
                  name: ga-config-map
                  key: MAIL_REPLY_TO
            - name: BUGSNAG_API_KEY
              valueFrom:
                configMapKeyRef:
                  name: ga-config-map
                  key: BUGSNAG_API_KEY
            - name: AWS_URL
              valueFrom:
                configMapKeyRef:
                  name: ga-config-map
                  key: AWS_URL
            - name: BASE_URL
              valueFrom:
                configMapKeyRef:
                  name: ga-config-map
                  key: BASE_URL

          name: graphacademy
          resources: {}
      restartPolicy: Always
status: {}
